version: "2"

services:
  ca-root.geodb.com:
    restart: always
    extends:
      file: ./ca-bootstrap-command.yaml
      service: ca-command
    image: hyperledger/fabric-ca:1.4.1
    container_name: ca-root.geodb.com
    ports:
      - 7500:7054
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - ./fabric-ca-server:/etc/hyperledger/fabric-ca-server
